# Generated by Django 5.0.6 on 2024-06-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="award_point",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateField(null=True),
        ),
    ]
