# Generated by Django 5.0.3 on 2024-04-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', '-location']},
        ),
    ]
