# Generated by Django 5.0.3 on 2024-03-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_date_created_user_dob_user_name_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-location']},
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-profile', '-total']},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['-event', '-price']},
        ),
    ]
