# Generated by Django 5.0.3 on 2024-03-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_event_options_alter_organizer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='total',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
    ]
