# Generated by Django 5.0.3 on 2024-03-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_ticket_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
