# Generated by Django 5.0.6 on 2024-06-04 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_organizer_total_revenue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ["-event", "-user"]},
        ),
        migrations.AddField(
            model_name="feedback",
            name="comment",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="event",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.event"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
