# Generated by Django 5.0.6 on 2024-06-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizer",
            name="logo",
            field=models.ImageField(default="images/logo.png", null=True, upload_to=""),
        ),
    ]
