# Generated by Django 5.0.6 on 2024-06-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_organizer_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizer",
            name="logo",
            field=models.ImageField(default="logo.png", null=True, upload_to=""),
        ),
    ]
