# Generated by Django 5.0.6 on 2024-06-05 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_pendingpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_bought",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
