name: Build and Push to Docker Hub

on:
  workflow_call:

jobs:
  validate-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4.0.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-Tickers
          restore-keys: |
            ${{ runner.os }}-docker-Tickers

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
      
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0 # Don't use @master or @v1 unless you're happy to test the latest version
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: false
          DEFAULT_BUMP: patch
          REALEASE_BRANCHS: master
          TAG_CONTEXT: branch

      - name: echo ??
        run: |
          echo ${{ github.sha }} > Release.txt

          
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          tag_name: ${{ steps.tag.outputs.new_tag }}
          body_path: "${{ github.workspace }}//release"

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tickers:latest , ${{ secrets.DOCKER_USERNAME }}/tickers:${{ steps.tag.outputs.new_tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
      
