name: Deploy app
on:
  workflow_dispatch: 

run-name: Deploy to VPS by @${{ github.actor }}

jobs:
  deploy-to-vps:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to VPC
        run: echo "Deploy successfully"

      - name: Re run container
        run: |
          cd /path/
          git pull
