name: Deploy app
on:
  workflow_dispatch: 

run-name: Deploy to VPS by @${{ github.actor }}

jobs:
  deploy-to-vps:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/booster/Tickers && git pull
            PID=$(sudo netstat -npl | awk '/:85/' | awk -F"[ /]+" '{print $7; exit}'); sudo kill -9 "$PID"
            nohup python3 manage.py runserver 85 --insecure &
            pwd

