name: Deploy app
on:
  workflow_dispatch: 
  workflow_call:

run-name: Deploy to VPS by @${{ github.actor }}

jobs:
  deploy-to-vps:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/booster && ./action

